import Header from "../components/Header"
import LotteryEntrance from "../components/LotteryEntrance"
import ManualHeader from "../components/ManualHeader"
import styles from "../styles/Home.module.css"
import Head from "next/head"

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Smart Contract Lottery</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* <ManualHeader /> */}
            <Header />
            <LotteryEntrance />
            hello
        </div>
    )
}
